import Link from "next/link";
import Navbar from "@/components/Navbar";

const LAST_UPDATED = "15 April 2026";
const CONTACT_EMAIL = "legal@promitly.com";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main style={{ minHeight: "100vh", paddingTop: 80 }}>
        <section style={{ padding: "60px 0 100px" }}>
          <div className="page" style={{ maxWidth: 720 }}>

            <div style={{ marginBottom: 40 }}>
              <div className="chip" style={{ marginBottom: 16 }}>Legal</div>
              <h1 style={{ fontFamily: "var(--font-sans)", fontSize: "clamp(26px,4vw,40px)", fontWeight: 700, color: "var(--text-1)", letterSpacing: "-0.02em", marginBottom: 10 }}>
                Terms of Service
              </h1>
              <p style={{ fontSize: 13, color: "var(--text-4)", fontFamily: "var(--font-mono)" }}>Last updated: {LAST_UPDATED}</p>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 36 }}>

              <Section title="1. Acceptance of terms">
                <P>By accessing or using PROMITLY ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service. These terms apply to all visitors, users, and registered account holders.</P>
              </Section>

              <Section title="2. Description of service">
                <P>PROMITLY is an AI prompt library providing curated, structured prompts for use with AI language models including but not limited to ChatGPT, Claude, Gemini, Grok, Mistral, DeepSeek, Llama, and Perplexity.</P>
                <P>The Service is provided free of charge for registered users. We reserve the right to introduce paid tiers in the future, with reasonable notice to existing users.</P>
              </Section>

              <Section title="3. Account registration">
                <P>To access premium prompts, saving features, and other account features, you must register for a free account. By registering, you agree to:</P>
                <UL items={[
                  "Provide accurate and complete information during registration.",
                  "Keep your login credentials secure and not share your account.",
                  "Notify us immediately of any unauthorised use of your account.",
                  "Be responsible for all activity that occurs under your account.",
                ]} />
                <P>You must be at least 13 years old to create an account. Users in the EU must be at least 16 years old, or have parental consent.</P>
              </Section>

              <Section title="4. Acceptable use">
                <P>You agree not to use the Service to:</P>
                <UL items={[
                  "Violate any applicable law or regulation.",
                  "Generate, distribute, or promote content that is illegal, harmful, threatening, abusive, defamatory, or discriminatory.",
                  "Attempt to gain unauthorised access to any part of the Service or its infrastructure.",
                  "Scrape, copy, or systematically extract prompt content for redistribution or commercial use without written permission.",
                  "Use automated bots or scripts to access the Service at scale.",
                  "Impersonate any person or entity.",
                ]} />
              </Section>

              <Section title="5. Intellectual property">
                <P>All prompt content, text, design, and code on PROMITLY is owned by PROMITLY or its licensors and is protected by copyright law. You may not reproduce, distribute, modify, or create derivative works from our content without explicit written permission.</P>
                <P><strong style={{ color: "var(--text-1)" }}>Personal use licence:</strong> We grant you a limited, non-exclusive, non-transferable licence to copy individual prompts for your own personal use with AI tools. This licence does not include the right to republish, sell, or distribute prompts as your own.</P>
              </Section>

              <Section title="6. AI output disclaimer">
                <P>PROMITLY provides prompts — instructions intended to guide AI models. We are not responsible for the outputs generated by third-party AI tools when using our prompts. AI-generated content may be inaccurate, incomplete, or inappropriate. Always review AI outputs before use in professional, legal, medical, or financial contexts.</P>
                <P>We do not guarantee that our prompts will produce any specific result with any particular AI model, as AI behaviour varies by provider, model version, and configuration.</P>
              </Section>

              <Section title="7. Privacy">
                <P>Your use of the Service is subject to our <Link href="/privacy" style={{ color: "var(--primary)" }}>Privacy Policy</Link>, which is incorporated into these Terms by reference. By using the Service, you consent to the data practices described in our Privacy Policy.</P>
              </Section>

              <Section title="8. Disclaimer of warranties">
                <P>The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that any defects will be corrected.</P>
                <P>To the fullest extent permitted by law, we disclaim all warranties including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</P>
              </Section>

              <Section title="9. Limitation of liability">
                <P>To the maximum extent permitted by applicable law, PROMITLY and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of or in connection with your use of the Service.</P>
                <P>In jurisdictions that do not allow the exclusion of certain warranties or limitation of liability, our liability is limited to the maximum extent permitted by law.</P>
              </Section>

              <Section title="10. Account termination">
                <P>You may delete your account at any time from the <Link href="/account" style={{ color: "var(--primary)" }}>Account page</Link>. Deletion is immediate and permanent.</P>
                <P>We reserve the right to suspend or terminate accounts that violate these Terms, engage in abusive behaviour, or for any reason at our discretion, with or without notice.</P>
              </Section>

              <Section title="11. Changes to terms">
                <P>We may modify these Terms at any time. We will notify registered users of material changes by email at least 14 days before they take effect. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.</P>
              </Section>

              <Section title="12. Governing law">
                <P>These Terms are governed by and construed in accordance with the laws of the European Union. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of the EU member state where PROMITLY operates.</P>
                <P>For EU consumers: nothing in these Terms affects your statutory rights under applicable consumer protection laws.</P>
              </Section>

              <Section title="13. Contact">
                <P>For legal enquiries or questions about these Terms:</P>
                <P><strong style={{ color: "var(--text-1)" }}>Email:</strong> <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--primary)" }}>{CONTACT_EMAIL}</a></P>
              </Section>

            </div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 style={{ fontFamily: "var(--font-sans)", fontSize: 18, fontWeight: 700, color: "var(--text-1)", marginBottom: 14, letterSpacing: "-0.01em" }}>{title}</h2>
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{children}</div>
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 14, color: "var(--text-2)", lineHeight: 1.8 }}>{children}</p>;
}

function UL({ items }: { items: string[] }) {
  return (
    <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
      {items.map(item => (
        <li key={item} style={{ fontSize: 14, color: "var(--text-2)", lineHeight: 1.7 }}>{item}</li>
      ))}
    </ul>
  );
}

function Footer() {
  return (
    <footer style={{ background: "var(--bg)", borderTop: "1px solid var(--border)", padding: "32px 0" }}>
      <div className="page" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12 }}>
        <Link href="/" style={{ fontFamily: "var(--font-sans)", fontSize: 15, fontWeight: 700, color: "var(--text-2)", textDecoration: "none" }}>promitly</Link>
        <span style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--text-4)" }}>© 2026 PROMITLY · All rights reserved</span>
        <div style={{ display: "flex", gap: 16 }}>
          {[["Privacy", "/privacy"], ["Terms", "/terms"], ["Contact", "/contact"]].map(([l, h]) => (
            <Link key={l} href={h} style={{ fontSize: 12, color: "var(--text-3)", textDecoration: "none" }}>{l}</Link>
          ))}
        </div>
      </div>
    </footer>
  );
}
